COCO_CATEGORIES = [
    {"id": 1, "name": "person", "supercategory": "object"},
    {"id": 2, "name": "bicycle", "supercategory": "object"},
    {"id": 3, "name": "car", "supercategory": "object"},
    {"id": 4, "name": "motorcycle", "supercategory": "object"},
    {"id": 5, "name": "airplane", "supercategory": "object"},
    {"id": 6, "name": "bus", "supercategory": "object"},
    {"id": 7, "name": "train", "supercategory": "object"},
    {"id": 8, "name": "truck", "supercategory": "object"},
    {"id": 9, "name": "boat", "supercategory": "object"},
    {"id": 10, "name": "traffic light", "supercategory": "object"},
    {"id": 11, "name": "fire hydrant", "supercategory": "object"},
    {"id": 12, "name": "__12__", "supercategory": "object"},
    {"id": 13, "name": "stop sign", "supercategory": "object"},
    {"id": 14, "name": "parking meter", "supercategory": "object"},
    {"id": 15, "name": "bench", "supercategory": "object"},
    {"id": 16, "name": "bird", "supercategory": "object"},
    {"id": 17, "name": "cat", "supercategory": "object"},
    {"id": 18, "name": "dog", "supercategory": "object"},
    {"id": 19, "name": "horse", "supercategory": "object"},
    {"id": 20, "name": "sheep", "supercategory": "object"},
    {"id": 21, "name": "cow", "supercategory": "object"},
    {"id": 22, "name": "elephant", "supercategory": "object"},
    {"id": 23, "name": "bear", "supercategory": "object"},
    {"id": 24, "name": "zebra", "supercategory": "object"},
    {"id": 25, "name": "giraffe", "supercategory": "object"},
    {"id": 26, "name": "__26__", "supercategory": "object"},
    {"id": 27, "name": "backpack", "supercategory": "object"},
    {"id": 28, "name": "umbrella", "supercategory": "object"},
    {"id": 29, "name": "__29__", "supercategory": "object"},
    {"id": 30, "name": "__30__", "supercategory": "object"},
    {"id": 31, "name": "handbag", "supercategory": "object"},
    {"id": 32, "name": "tie", "supercategory": "object"},
    {"id": 33, "name": "suitcase", "supercategory": "object"},
    {"id": 34, "name": "frisbee", "supercategory": "object"},
    {"id": 35, "name": "skis", "supercategory": "object"},
    {"id": 36, "name": "snowboard", "supercategory": "object"},
    {"id": 37, "name": "sports ball", "supercategory": "object"},
    {"id": 38, "name": "kite", "supercategory": "object"},
    {"id": 39, "name": "baseball bat", "supercategory": "object"},
    {"id": 40, "name": "baseball glove", "supercategory": "object"},
    {"id": 41, "name": "skateboard", "supercategory": "object"},
    {"id": 42, "name": "surfboard", "supercategory": "object"},
    {"id": 43, "name": "tennis racket", "supercategory": "object"},
    {"id": 44, "name": "bottle", "supercategory": "object"},
    {"id": 45, "name": "__45__", "supercategory": "object"},
    {"id": 46, "name": "wine glass", "supercategory": "object"},
    {"id": 47, "name": "cup", "supercategory": "object"},
    {"id": 48, "name": "fork", "supercategory": "object"},
    {"id": 49, "name": "knife", "supercategory": "object"},
    {"id": 50, "name": "spoon", "supercategory": "object"},
    {"id": 51, "name": "bowl", "supercategory": "object"},
    {"id": 52, "name": "banana", "supercategory": "object"},
    {"id": 53, "name": "apple", "supercategory": "object"},
    {"id": 54, "name": "sandwich", "supercategory": "object"},
    {"id": 55, "name": "orange", "supercategory": "object"},
    {"id": 56, "name": "broccoli", "supercategory": "object"},
    {"id": 57, "name": "carrot", "supercategory": "object"},
    {"id": 58, "name": "hot dog", "supercategory": "object"},
    {"id": 59, "name": "pizza", "supercategory": "object"},
    {"id": 60, "name": "donut", "supercategory": "object"},
    {"id": 61, "name": "cake", "supercategory": "object"},
    {"id": 62, "name": "chair", "supercategory": "object"},
    {"id": 63, "name": "couch", "supercategory": "object"},
    {"id": 64, "name": "potted plant", "supercategory": "object"},
    {"id": 65, "name": "bed", "supercategory": "object"},
    {"id": 66, "name": "__66__", "supercategory": "object"},
    {"id": 67, "name": "dining table", "supercategory": "object"},
    {"id": 68, "name": "__68__", "supercategory": "object"},
    {"id": 69, "name": "__69__", "supercategory": "object"},
    {"id": 70, "name": "toilet", "supercategory": "object"},
    {"id": 71, "name": "__71__", "supercategory": "object"},
    {"id": 72, "name": "tv", "supercategory": "object"},
    {"id": 73, "name": "laptop", "supercategory": "object"},
    {"id": 74, "name": "mouse", "supercategory": "object"},
    {"id": 75, "name": "remote", "supercategory": "object"},
    {"id": 76, "name": "keyboard", "supercategory": "object"},
    {"id": 77, "name": "cell phone", "supercategory": "object"},
    {"id": 78, "name": "microwave", "supercategory": "object"},
    {"id": 79, "name": "oven", "supercategory": "object"},
    {"id": 80, "name": "toaster", "supercategory": "object"},
    {"id": 81, "name": "sink", "supercategory": "object"},
    {"id": 82, "name": "refrigerator", "supercategory": "object"},
    {"id": 83, "name": "__83__", "supercategory": "object"},
    {"id": 84, "name": "book", "supercategory": "object"},
    {"id": 85, "name": "clock", "supercategory": "object"},
    {"id": 86, "name": "vase", "supercategory": "object"},
    {"id": 87, "name": "scissors", "supercategory": "object"},
    {"id": 88, "name": "teddy bear", "supercategory": "object"},
    {"id": 89, "name": "hair drier", "supercategory": "object"},
    {"id": 90, "name": "toothbrush", "supercategory": "object"},
]

TEC_COCO_CATEGORIES = [
    # BACKGROUND
    {"id": 0, "coco_id": 0, "name": "__background__", "supercategory": "__background__"},
    # BIRD
    {"id": 1, "coco_id": 16, "name": "bird", "supercategory": "object"},
    # DRONE
    {"id": 2, "coco_id": None, "name": "drone", "supercategory": "object"},
    # AIRCRAFT
    {"id": 3, "coco_id": 5, "name": "airplane", "supercategory": "object"},
    {"id": 4, "coco_id": None, "name": "helicopter", "supercategory": "object"},
    # VEHICLE
    {"id": 5, "coco_id": 3, "name": "car", "supercategory": "object"},
    {"id": 6, "coco_id": 6, "name": "bus", "supercategory": "object"},
    {"id": 7, "coco_id": 7, "name": "train", "supercategory": "object"},
    {"id": 8, "coco_id": 8, "name": "truck", "supercategory": "object"},
    # BOAT
    {"id": 9, "coco_id": 9, "name": "boat", "supercategory": "object"},
    # BIKE
    {"id": 10, "coco_id": 4, "name": "motorcycle", "supercategory": "object"},
    {"id": 11, "coco_id": 2, "name": "bicycle", "supercategory": "object"},
    # PERSON
    {"id": 12, "coco_id": 1, "name": "person", "supercategory": "object"},
    # ANIMAL
    {"id": 13, "coco_id": 17, "name": "cat", "supercategory": "object"},
    {"id": 14, "coco_id": 18, "name": "dog", "supercategory": "object"},
    {"id": 15, "coco_id": 19, "name": "horse", "supercategory": "object"},
    {"id": 16, "coco_id": 20, "name": "sheep", "supercategory": "object"},
    {"id": 17, "coco_id": 21, "name": "cow", "supercategory": "object"},
    {"id": 18, "coco_id": 22, "name": "elephant", "supercategory": "object"},
    {"id": 19, "coco_id": 23, "name": "bear", "supercategory": "object"},
    {"id": 20, "coco_id": 24, "name": "zebra", "supercategory": "object"},
    {"id": 21, "coco_id": 25, "name": "giraffe", "supercategory": "object"}
]
